### ISSUE TITLE
Method invocation failed because [Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken' AADTool

### ISSUE THREAD

**Issue by PixelRobots** [robotechredmond/Azure-PowerShell-Snippets#9]
When running the AADTool's I keep getting this error.

Method invocation failed because
[Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does not contain a method named 'AcquireToken'

What do I need to do to fix?

**Comment by ruandersMSFT** [comment]
@PixelRobots  Newer versions of the AAD Authentication have replaced AcquireToken with AcquireTokenAsync.  

As an example, replace:

$accessToken = $authenticationContext.AcquireToken($resourceUrl, $clientId, $redirectUrl, [Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior]::RefreshSession).AccessToken

With:

$PromptBehavior = [Microsoft.IdentityModel.Clients.ActiveDirectory.PromptBehavior]::RefreshSession
$PlatformParameters = New-Object Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters -ArgumentList $PromptBehavior
$accessToken = $authenticationContext.AcquireTokenAsync($resourceUrl, $clientId, $redirectUrl, $PlatformParameters).Result.AccessToken

**Comment by PixelRobots** [comment]
Perfect that works now.
